# Enable flakes permanent
# https://nixos.wiki/wiki/Flakes#Permanent
experimental-features = nix-command flakes

# Binary Cache for haskell.nix
extra-substituters = https://cache.iog.io
extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
